<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from numpy.linalg import eig

A = np.array([[-12,3],[4,1]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B=np.array([[0],[0]])
print(B)

X=np.dot(inv_A,B)
print(X)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0]
 [0]]
[[0.]
 [0.]]


In [14]:
A=np.array([[-6,3],[4,5]])
print(A)

w,v=np.linalg.eig(A)
print("The eigenvalue/s is/are",w)
print("The eigenvector/s is/are",v)

[[-6  3]
 [ 4  5]]
The eigenvalue/s is/are [-7.  6.]
The eigenvector/s is/are [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]


In [22]:
A=np.array([[2,2,4],[1,3,5],[2,3,4]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalue/s is/are:",w.round())
print("The eigenvector/s is/are:",v.round())

x=np.dot(A,v.round())
print(x)

X=np.array([[-1],[-1],[-0]])
Y=np.array([[-1],[1],[-1]])
Z=np.array([[-1],[-0],[-1]])


d=np.dot(A,X)
print(d)
e=np.dot(A,Y)
print(e)
f=np.dot(A,Z)
print(f)

[[2 2 4]
 [1 3 5]
 [2 3 4]]
The eigenvalue/s is/are: [ 9.  1. -1.]
The eigenvector/s is/are: [[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]
[[-4]
 [-4]
 [-5]]
[[-4]
 [-3]
 [-3]]
[[-6]
 [-6]
 [-6]]
