<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Problem 1

In [15]:
#inputs the given
A=np.array([[1,1,1],[1,0,4],[0,0,5]])
print(f'Matrix A;\n {A}')
#prints the Matrix A
print()
#inputs the given
B=np.array([[89],[89],[95]])
#prints the Matrix B
print(f'Matrix B;\n {A}')
#gets the inverse
C=np.linalg.inv(A).dot(B)
print(f'Inverse of Matrix A;\n {C}')

Matrix A;
 [[1 1 1]
 [1 0 4]
 [0 0 5]]

Matrix B;
 [[1 1 1]
 [1 0 4]
 [0 0 5]]
Inverse of Matrix A;
 [[13.]
 [57.]
 [19.]]


Problem 2

In [14]:
import numpy as np
#inputs the given
A=np.array([[3,-1,1],[9,-3,3],[-12,4,-4]])
B=np.array([[5],[15],[-20]])
#gets the inverse of A
C=np.linalg.pinv(A)
#prints the inverse of A
print(C)
#multiply C with B
D=np.dot(C,B)
print(D)
#then lastly multiply A with D
E=np.dot(A,D)

[[ 0.01048951  0.03146853 -0.04195804]
 [-0.0034965  -0.01048951  0.01398601]
 [ 0.0034965   0.01048951 -0.01398601]]
[[ 1.36363636]
 [-0.45454545]
 [ 0.45454545]]


Problem 3

In [9]:
import numpy as np
from numpy.linalg import eig
#inputs the given
A = np.array([[8,5,-6],[-12,-9,12],[-3,-3,5]])
#prints the egeinvalues and eigenvectors
print(A,"\n")
w,v = np.linalg.eig(A) 
print("The eigenvalue/s is/are:\n",w.round(),"\n")
print("The eigenvector/s is/are:\n",v.round())

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]] 

The eigenvalue/s is/are:
 [-1.  3.  2.] 

The eigenvector/s is/are:
 [[ 0. -1.  1.]
 [-1.  1.  0.]
 [-0. -0.  1.]]
