<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Matrix_inverse_and_transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3X3 MATRIX inverse and its transpose

In [6]:
import numpy as np
A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
B=(np.linalg.inv(A))
print(B)

[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [1]:

A=np.array([[6,1,1],[4,-2,5],[2,8,7]])
print(A)
B=np.transpose(A)
print(B)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


4X4 MATRIX inverse and its transpose

In [15]:
A = np.array([[1, 2, 3, 4], [23, 42, 14, 25],[21, 3, 34, 8],[20, 43, 12, 18]])
  
B = np.linalg.inv(A)
print(B)

[[-0.45753564  0.17539327  0.02163584 -0.15154311]
 [ 0.0869124  -0.08534391 -0.00894958  0.10319694]
 [ 0.24214605 -0.12206486  0.0207132   0.10651843]
 [ 0.13931817  0.09037228 -0.01646907 -0.09360151]]


In [16]:
A=np.array([[1, 2, 3, 4], [23, 42, 14, 25],[21, 3, 34, 8],[20, 43, 12, 18]])
print(A)
B=np.transpose(A)
print(B)

[[ 1  2  3  4]
 [23 42 14 25]
 [21  3 34  8]
 [20 43 12 18]]
[[ 1 23 21 20]
 [ 2 42  3 43]
 [ 3 14 34 12]
 [ 4 25  8 18]]
