<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [1]:
import numpy as np
#made a square matrix with the lenght of 5
A=np.array([[1,2,3,4,5],[6,7,8,9,10],[10,9,8,7,6],[5,4,3,2,1],[1,3,5,7,9]])
#prints the 5 lenght matrix
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [10  9  8  7  6]
 [ 5  4  3  2  1]
 [ 1  3  5  7  9]]


Question 2

In [13]:
#made a square matrix which the elements below the principal diagonal are zero
A = np.array([[1,1,1,1],[0,1,1,1],[0,0,1,1],[0,0,0,1]])
#prints the matrix
print(A)

[[1 1 1 1]
 [0 1 1 1]
 [0 0 1 1]
 [0 0 0 1]]


Question 3

In [14]:
#made a symmetrical matrix
A=np.array([[2,4,6],[4,8,10],[6,10,2]])
#prints the symmetrical matrix
print(A)

[[ 2  4  6]
 [ 4  8 10]
 [ 6 10  2]]


Question 4

In [2]:
#inputted the given matrix
A=np.array([[1,2,3],[2,3,3],[3,4,-2]])
#Gets the inverse of the given Matrix which is declared as A
B=(np.linalg.inv(A))
#prints the inverse of the matrix
print(B)

[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5

In [15]:
#inputs the given matrix
A=np.array([[1,2,3],[2,3,3],[3,4,-2]])
#prints the given matrix
print(A)
#gets the determinant of the given matrix
print(np.linalg.det(A))
#gets the round off of it
print(round(np.linalg.det(A)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
5.000000000000001
5


Question 6

In [20]:
#inputs the given
A = np.array([[5,4,1],[10,9,4],[10,13,15]])
B = np.array( [[3.4],[8.8],[19.2]])
#gets the root of given
C = np.linalg.inv(A) @ B
#prints the root
print(C)

[[0.2]
 [0.4]
 [0.8]]
