<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. A

In [14]:
import numpy as np

W = np.array ([[1,-3],[2,-2],[3,1]])
print("Vector W is", W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [20]:
import numpy as np

Y = np.array ([[1,2,0],[0,-1,2]])
print("Vector Y is", Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [21]:
print(np.dot(W, Y))

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


B

In [11]:
import numpy as np
Z = np.array ([[0,1],[2,3]])
print("Vector Z is", Z)

Vector Z is [[0 1]
 [2 3]]


In [12]:
R = np.add(Z,Z)
R

array([[0, 2],
       [4, 6]])

C

In [22]:
import numpy as np

X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
print("Vector X is", X)
print()
print(3*X)

Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2. A

In [23]:
import numpy as np

W = np.array ([[1,-3],[2,-2],[3,1]])
print("Vector W is", W)

Vector W is [[ 1 -3]
 [ 2 -2]
 [ 3  1]]


In [24]:
import numpy as np

Y = np.array ([[1,2,0],[0,-1,2]])
print("Vector Y is", Y)

Vector Y is [[ 1  2  0]
 [ 0 -1  2]]


In [37]:
print(np.dot(Y, W)^2)

[[ 7 -5]
 [ 6  6]]


B

In [ ]:
import numpy as np

W = np.array ([[1,-3],[2,-2],[3,1]])
print("Vector W is", W)

In [ ]:
import numpy as np

Y = np.array ([[1,2,0],[0,-1,2]])
print("Vector Y is", Y)

In [33]:
import numpy as np

X = np.array ([[3,2,1],[-1,2,3],[2,-1,1]])
print("Vector X is", X)

Vector X is [[ 3  2  1]
 [-1  2  3]
 [ 2 -1  1]]


In [32]:
R = np.dot(W,Y)
R

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

In [34]:
print(np.subtract(R, X))

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


C

In [ ]:
import numpy as np

W = np.array ([[1,-3],[2,-2],[3,1]])
print("Vector W is", W)

In [ ]:
import numpy as np

Y = np.array ([[1,2,0],[0,-1,2]])
print("Vector Y is", Y)

In [38]:
import numpy as np

Z = np.array ([[0,1],[2,3]])
print("Vector Z is", Z)

Vector Z is [[0 1]
 [2 3]]


In [46]:
print("(YW - Z^2)")
print(np.dot(Y,W)-Z^2)

(YW - Z^2)
[[ 7 -6]
 [ 0  3]]
