<a href="https://colab.research.google.com/github/maglelongshane/Linera-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Spaces and Its Operations

In [1]:
import numpy as np
A = np.array([4,3])
B = np.array([2,-5])

print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [2]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape

(2, 3)

In [3]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
print(pool.shape)
print(pool.size)

(2, 3)
6


In [5]:
import numpy as np
ball1 = np.array ([1,2,3])
ball2 = np.array ([0,1,-1])
pool = np.array ([ball1,ball2])
pool.shape
pool.ndim

2

In [4]:
U = np.array ([[1,2,3,],[4,5,6]])
U

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
U = np.array ([[1,2,3,],[4,5,6]])
U.shape

(2, 3)

In [7]:
U = np.array ([[1,2,3,],[4,5,6]])
U.ndim

2

In [8]:
U = np.array ([[1,2,3,],[4,5,6]])
U.size

6

In [9]:
U = np.array ([[1,2,3,],[4,5,6]])
U
U.size

6

Addition of Vectors

In [10]:
R = A+B
print(R)

[ 6 -2]


In [11]:
R = np.add(A,B)
R

array([ 6, -2])

Vector Subraction

In [12]:
R = np.subtract(A,B)
R

array([2, 8])

Vector Scaling

In [13]:
A = np.array([1,5,8,9])
S = 5*A
S

array([ 5, 25, 40, 45])

In [14]:

A = np.array([1,5,8,9])
S = np.multiply(5,A)
S

array([ 5, 25, 40, 45])

Vector Cross Product

In [17]:
#initialize arrays
A = np.array([2,3,4])
B = np.array([1,7,0])

#compute cross product
output = np.cross(A,B)
print(output)

[-28   4  11]


In [18]:
#compute the dot product of A and B
output = np.dot(A,B)
print(output)

23
